
[window]
#opacity = 0.85
#todo hacer el pr con los temas , faltan las fotos y el readme.
padding = { x = 2, y = 2 }
dynamic_padding = true
decorations = "full"
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16.0

[font.normal]
family = "Monoid Nerd Font Mono"
style = "Retina"

[font.bold]
family = "Monoid Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[cursor]
style = "Block"
unfocused_hollow = false

[keyboard]
# Tus atajos de teclado actuales
[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "Control"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[general]
# Configuración de Alacritty con temas Spacemacs (Dark y Light)
import = [
 "~/.config/alacritty/themes/themes/spacemacs-dark.toml"
]

